//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace GASystem.DataModel {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ExposedHoursGroupViewDS")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ExposedHoursGroupViewDS : global::System.Data.DataSet {
        
        private GAExposedHoursGroupViewDataTable tableGAExposedHoursGroupView;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ExposedHoursGroupViewDS() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected ExposedHoursGroupViewDS(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["GAExposedHoursGroupView"] != null)) {
                    base.Tables.Add(new GAExposedHoursGroupViewDataTable(ds.Tables["GAExposedHoursGroupView"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GAExposedHoursGroupViewDataTable GAExposedHoursGroupView {
            get {
                return this.tableGAExposedHoursGroupView;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            ExposedHoursGroupViewDS cln = ((ExposedHoursGroupViewDS)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["GAExposedHoursGroupView"] != null)) {
                    base.Tables.Add(new GAExposedHoursGroupViewDataTable(ds.Tables["GAExposedHoursGroupView"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableGAExposedHoursGroupView = ((GAExposedHoursGroupViewDataTable)(base.Tables["GAExposedHoursGroupView"]));
            if ((initTable == true)) {
                if ((this.tableGAExposedHoursGroupView != null)) {
                    this.tableGAExposedHoursGroupView.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "ExposedHoursGroupViewDS";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ExposedHoursGroupViewDS.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableGAExposedHoursGroupView = new GAExposedHoursGroupViewDataTable();
            base.Tables.Add(this.tableGAExposedHoursGroupView);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeGAExposedHoursGroupView() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ExposedHoursGroupViewDS ds = new ExposedHoursGroupViewDS();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void GAExposedHoursGroupViewRowChangeEventHandler(object sender, GAExposedHoursGroupViewRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class GAExposedHoursGroupViewDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnExposedHoursGroupViewRowId;
            
            private global::System.Data.DataColumn columnDateTimeFrom;
            
            private global::System.Data.DataColumn columnDateTimeTo;
            
            private global::System.Data.DataColumn columnDepartmentCategoryListsRowId;
            
            private global::System.Data.DataColumn columnWatchListsRowId;
            
            private global::System.Data.DataColumn columnViewTypeListsRowId;
            
            private global::System.Data.DataColumn columnNumberOfPersons;
            
            private global::System.Data.DataColumn columnExposedHoursPerWorkDay;
            
            private global::System.Data.DataColumn columnExposedDaysPerWeek;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GAExposedHoursGroupViewDataTable() {
                this.TableName = "GAExposedHoursGroupView";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal GAExposedHoursGroupViewDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected GAExposedHoursGroupViewDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ExposedHoursGroupViewRowIdColumn {
                get {
                    return this.columnExposedHoursGroupViewRowId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DateTimeFromColumn {
                get {
                    return this.columnDateTimeFrom;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DateTimeToColumn {
                get {
                    return this.columnDateTimeTo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DepartmentCategoryListsRowIdColumn {
                get {
                    return this.columnDepartmentCategoryListsRowId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn WatchListsRowIdColumn {
                get {
                    return this.columnWatchListsRowId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ViewTypeListsRowIdColumn {
                get {
                    return this.columnViewTypeListsRowId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NumberOfPersonsColumn {
                get {
                    return this.columnNumberOfPersons;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ExposedHoursPerWorkDayColumn {
                get {
                    return this.columnExposedHoursPerWorkDay;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ExposedDaysPerWeekColumn {
                get {
                    return this.columnExposedDaysPerWeek;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GAExposedHoursGroupViewRow this[int index] {
                get {
                    return ((GAExposedHoursGroupViewRow)(this.Rows[index]));
                }
            }
            
            public event GAExposedHoursGroupViewRowChangeEventHandler GAExposedHoursGroupViewRowChanging;
            
            public event GAExposedHoursGroupViewRowChangeEventHandler GAExposedHoursGroupViewRowChanged;
            
            public event GAExposedHoursGroupViewRowChangeEventHandler GAExposedHoursGroupViewRowDeleting;
            
            public event GAExposedHoursGroupViewRowChangeEventHandler GAExposedHoursGroupViewRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddGAExposedHoursGroupViewRow(GAExposedHoursGroupViewRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GAExposedHoursGroupViewRow AddGAExposedHoursGroupViewRow(System.DateTime DateTimeFrom, System.DateTime DateTimeTo, int DepartmentCategoryListsRowId, int WatchListsRowId, int ViewTypeListsRowId, int NumberOfPersons, int ExposedHoursPerWorkDay, int ExposedDaysPerWeek) {
                GAExposedHoursGroupViewRow rowGAExposedHoursGroupViewRow = ((GAExposedHoursGroupViewRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        DateTimeFrom,
                        DateTimeTo,
                        DepartmentCategoryListsRowId,
                        WatchListsRowId,
                        ViewTypeListsRowId,
                        NumberOfPersons,
                        ExposedHoursPerWorkDay,
                        ExposedDaysPerWeek};
                rowGAExposedHoursGroupViewRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowGAExposedHoursGroupViewRow);
                return rowGAExposedHoursGroupViewRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GAExposedHoursGroupViewRow FindByExposedHoursGroupViewRowId(int ExposedHoursGroupViewRowId) {
                return ((GAExposedHoursGroupViewRow)(this.Rows.Find(new object[] {
                            ExposedHoursGroupViewRowId})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                GAExposedHoursGroupViewDataTable cln = ((GAExposedHoursGroupViewDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new GAExposedHoursGroupViewDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnExposedHoursGroupViewRowId = base.Columns["ExposedHoursGroupViewRowId"];
                this.columnDateTimeFrom = base.Columns["DateTimeFrom"];
                this.columnDateTimeTo = base.Columns["DateTimeTo"];
                this.columnDepartmentCategoryListsRowId = base.Columns["DepartmentCategoryListsRowId"];
                this.columnWatchListsRowId = base.Columns["WatchListsRowId"];
                this.columnViewTypeListsRowId = base.Columns["ViewTypeListsRowId"];
                this.columnNumberOfPersons = base.Columns["NumberOfPersons"];
                this.columnExposedHoursPerWorkDay = base.Columns["ExposedHoursPerWorkDay"];
                this.columnExposedDaysPerWeek = base.Columns["ExposedDaysPerWeek"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnExposedHoursGroupViewRowId = new global::System.Data.DataColumn("ExposedHoursGroupViewRowId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExposedHoursGroupViewRowId);
                this.columnDateTimeFrom = new global::System.Data.DataColumn("DateTimeFrom", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDateTimeFrom);
                this.columnDateTimeTo = new global::System.Data.DataColumn("DateTimeTo", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDateTimeTo);
                this.columnDepartmentCategoryListsRowId = new global::System.Data.DataColumn("DepartmentCategoryListsRowId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDepartmentCategoryListsRowId);
                this.columnWatchListsRowId = new global::System.Data.DataColumn("WatchListsRowId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWatchListsRowId);
                this.columnViewTypeListsRowId = new global::System.Data.DataColumn("ViewTypeListsRowId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnViewTypeListsRowId);
                this.columnNumberOfPersons = new global::System.Data.DataColumn("NumberOfPersons", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNumberOfPersons);
                this.columnExposedHoursPerWorkDay = new global::System.Data.DataColumn("ExposedHoursPerWorkDay", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExposedHoursPerWorkDay);
                this.columnExposedDaysPerWeek = new global::System.Data.DataColumn("ExposedDaysPerWeek", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExposedDaysPerWeek);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnExposedHoursGroupViewRowId}, true));
                this.columnExposedHoursGroupViewRowId.AutoIncrement = true;
                this.columnExposedHoursGroupViewRowId.AllowDBNull = false;
                this.columnExposedHoursGroupViewRowId.ReadOnly = true;
                this.columnExposedHoursGroupViewRowId.Unique = true;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GAExposedHoursGroupViewRow NewGAExposedHoursGroupViewRow() {
                return ((GAExposedHoursGroupViewRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new GAExposedHoursGroupViewRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(GAExposedHoursGroupViewRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GAExposedHoursGroupViewRowChanged != null)) {
                    this.GAExposedHoursGroupViewRowChanged(this, new GAExposedHoursGroupViewRowChangeEvent(((GAExposedHoursGroupViewRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GAExposedHoursGroupViewRowChanging != null)) {
                    this.GAExposedHoursGroupViewRowChanging(this, new GAExposedHoursGroupViewRowChangeEvent(((GAExposedHoursGroupViewRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GAExposedHoursGroupViewRowDeleted != null)) {
                    this.GAExposedHoursGroupViewRowDeleted(this, new GAExposedHoursGroupViewRowChangeEvent(((GAExposedHoursGroupViewRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GAExposedHoursGroupViewRowDeleting != null)) {
                    this.GAExposedHoursGroupViewRowDeleting(this, new GAExposedHoursGroupViewRowChangeEvent(((GAExposedHoursGroupViewRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveGAExposedHoursGroupViewRow(GAExposedHoursGroupViewRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ExposedHoursGroupViewDS ds = new ExposedHoursGroupViewDS();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "GAExposedHoursGroupViewDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class GAExposedHoursGroupViewRow : global::System.Data.DataRow {
            
            private GAExposedHoursGroupViewDataTable tableGAExposedHoursGroupView;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal GAExposedHoursGroupViewRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableGAExposedHoursGroupView = ((GAExposedHoursGroupViewDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ExposedHoursGroupViewRowId {
                get {
                    return ((int)(this[this.tableGAExposedHoursGroupView.ExposedHoursGroupViewRowIdColumn]));
                }
                set {
                    this[this.tableGAExposedHoursGroupView.ExposedHoursGroupViewRowIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime DateTimeFrom {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableGAExposedHoursGroupView.DateTimeFromColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DateTimeFrom\' in table \'GAExposedHoursGroupView\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableGAExposedHoursGroupView.DateTimeFromColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime DateTimeTo {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableGAExposedHoursGroupView.DateTimeToColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DateTimeTo\' in table \'GAExposedHoursGroupView\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGAExposedHoursGroupView.DateTimeToColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int DepartmentCategoryListsRowId {
                get {
                    try {
                        return ((int)(this[this.tableGAExposedHoursGroupView.DepartmentCategoryListsRowIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DepartmentCategoryListsRowId\' in table \'GAExposedHoursGroup" +
                                "View\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGAExposedHoursGroupView.DepartmentCategoryListsRowIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int WatchListsRowId {
                get {
                    try {
                        return ((int)(this[this.tableGAExposedHoursGroupView.WatchListsRowIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'WatchListsRowId\' in table \'GAExposedHoursGroupView\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableGAExposedHoursGroupView.WatchListsRowIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ViewTypeListsRowId {
                get {
                    try {
                        return ((int)(this[this.tableGAExposedHoursGroupView.ViewTypeListsRowIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ViewTypeListsRowId\' in table \'GAExposedHoursGroupView\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableGAExposedHoursGroupView.ViewTypeListsRowIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int NumberOfPersons {
                get {
                    try {
                        return ((int)(this[this.tableGAExposedHoursGroupView.NumberOfPersonsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NumberOfPersons\' in table \'GAExposedHoursGroupView\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableGAExposedHoursGroupView.NumberOfPersonsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ExposedHoursPerWorkDay {
                get {
                    try {
                        return ((int)(this[this.tableGAExposedHoursGroupView.ExposedHoursPerWorkDayColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ExposedHoursPerWorkDay\' in table \'GAExposedHoursGroupView\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGAExposedHoursGroupView.ExposedHoursPerWorkDayColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ExposedDaysPerWeek {
                get {
                    try {
                        return ((int)(this[this.tableGAExposedHoursGroupView.ExposedDaysPerWeekColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ExposedDaysPerWeek\' in table \'GAExposedHoursGroupView\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableGAExposedHoursGroupView.ExposedDaysPerWeekColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDateTimeFromNull() {
                return this.IsNull(this.tableGAExposedHoursGroupView.DateTimeFromColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDateTimeFromNull() {
                this[this.tableGAExposedHoursGroupView.DateTimeFromColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDateTimeToNull() {
                return this.IsNull(this.tableGAExposedHoursGroupView.DateTimeToColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDateTimeToNull() {
                this[this.tableGAExposedHoursGroupView.DateTimeToColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDepartmentCategoryListsRowIdNull() {
                return this.IsNull(this.tableGAExposedHoursGroupView.DepartmentCategoryListsRowIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDepartmentCategoryListsRowIdNull() {
                this[this.tableGAExposedHoursGroupView.DepartmentCategoryListsRowIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsWatchListsRowIdNull() {
                return this.IsNull(this.tableGAExposedHoursGroupView.WatchListsRowIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetWatchListsRowIdNull() {
                this[this.tableGAExposedHoursGroupView.WatchListsRowIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsViewTypeListsRowIdNull() {
                return this.IsNull(this.tableGAExposedHoursGroupView.ViewTypeListsRowIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetViewTypeListsRowIdNull() {
                this[this.tableGAExposedHoursGroupView.ViewTypeListsRowIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNumberOfPersonsNull() {
                return this.IsNull(this.tableGAExposedHoursGroupView.NumberOfPersonsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNumberOfPersonsNull() {
                this[this.tableGAExposedHoursGroupView.NumberOfPersonsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsExposedHoursPerWorkDayNull() {
                return this.IsNull(this.tableGAExposedHoursGroupView.ExposedHoursPerWorkDayColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetExposedHoursPerWorkDayNull() {
                this[this.tableGAExposedHoursGroupView.ExposedHoursPerWorkDayColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsExposedDaysPerWeekNull() {
                return this.IsNull(this.tableGAExposedHoursGroupView.ExposedDaysPerWeekColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetExposedDaysPerWeekNull() {
                this[this.tableGAExposedHoursGroupView.ExposedDaysPerWeekColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class GAExposedHoursGroupViewRowChangeEvent : global::System.EventArgs {
            
            private GAExposedHoursGroupViewRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GAExposedHoursGroupViewRowChangeEvent(GAExposedHoursGroupViewRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GAExposedHoursGroupViewRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace GASystem.DataModel.ExposedHoursGroupViewDSTableAdapters {
    
    
    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.ComponentModel.DataObjectAttribute(true)]
    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class GAExposedHoursGroupViewTableAdapter : global::System.ComponentModel.Component {
        
        private global::System.Data.SqlClient.SqlDataAdapter _adapter;
        
        private global::System.Data.SqlClient.SqlConnection _connection;
        
        private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public GAExposedHoursGroupViewTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal global::System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected global::System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "GAExposedHoursGroupView";
            tableMapping.ColumnMappings.Add("ExposedHoursGroupViewRowId", "ExposedHoursGroupViewRowId");
            tableMapping.ColumnMappings.Add("DateTimeFrom", "DateTimeFrom");
            tableMapping.ColumnMappings.Add("DateTimeTo", "DateTimeTo");
            tableMapping.ColumnMappings.Add("DepartmentCategoryListsRowId", "DepartmentCategoryListsRowId");
            tableMapping.ColumnMappings.Add("WatchListsRowId", "WatchListsRowId");
            tableMapping.ColumnMappings.Add("ViewTypeListsRowId", "ViewTypeListsRowId");
            tableMapping.ColumnMappings.Add("NumberOfPersons", "NumberOfPersons");
            tableMapping.ColumnMappings.Add("ExposedHoursPerWorkDay", "ExposedHoursPerWorkDay");
            tableMapping.ColumnMappings.Add("ExposedDaysPerWeek", "ExposedDaysPerWeek");
            this._adapter.TableMappings.Add(tableMapping);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new global::System.Data.SqlClient.SqlConnection();
            this._connection.ConnectionString = global::GASystem.Properties.Settings.Default.flagdata20080117ConnectionString;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
            this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "SELECT ExposedHoursGroupViewRowId, DateTimeFrom, DateTimeTo, DepartmentCategoryLi" +
                "stsRowId, WatchListsRowId, ViewTypeListsRowId, NumberOfPersons, ExposedHoursPerW" +
                "orkDay, ExposedDaysPerWeek FROM dbo.GAExposedHoursGroupView";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(ExposedHoursGroupViewDS.GAExposedHoursGroupViewDataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual ExposedHoursGroupViewDS.GAExposedHoursGroupViewDataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            ExposedHoursGroupViewDS.GAExposedHoursGroupViewDataTable dataTable = new ExposedHoursGroupViewDS.GAExposedHoursGroupViewDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
    }
}

#pragma warning restore 1591